/* !!! Do not manually modify this file in the production stage !!!
 * This file is automatically created by MakeResBin.exe,
 * and used in the production stage.*/

#ifndef __RES_H_
#define __RES_H_

#define         RES_ICON_PCCAM_MODE     	0
#define         RES_ICON_POWER_OFF      	1
#define         RES_ICON_POWER_ON       	2
#define         RES_ICON_USB_MODE       	3
#define         RES_MUSIC_KEY_SOUND     	4
#define         RES_MUSIC_POWER_OFF     	5
#define         RES_MUSIC_POWER_ON      	6
#define         RES_OSD_SOURCE          	7
#define         RES_PALETTE             	8
#define         RES_RESFONT             	9
#define         RES_RESFONTIDX          	10
#define         RES_STR_VERSION         	11
#define         RES_TAKE_PHOTO_MUSIC    	12

#endif
